### ISSUE TITLE
Having more than 1 NumeralInput on a page brings focus to the last one

### ISSUE THREAD

**Issue by michaelryancaputo** [blackbing/react-numeral-input#1]
I have a form with multiple NumeralInput's on it. If a key is pressed on the 1st input it automatically tabs down to the last input. This seems to only happen in Safari.

**Comment by michaelryancaputo** [comment]
This doesn't seem to be an issue on version 0.0.8 of the component.

**Comment by blackbing** [comment]
@michaelryancaputo , thank you. I'm trying to solve editing problem. I removed this algorithm temporary. I will add some test case to test this feature. Please update to 0.1.1. thanks.

**Comment by michaelryancaputo** [comment]
Thank you!
