### ISSUE TITLE
cursor jumps to end when typing

### ISSUE THREAD

**Issue by aktxyz** [blackbing/react-numeral-input#2]
I notice when you try to edit a number and are not at the end of the input field, the cursor will jump to the end of the field when you press a key.   Would likely use this without that issue.

**Comment by blackbing** [comment]
Yea, I'm figuring out how to solve this problem, will update soon.

**Comment by blackbing** [comment]
the main idea is to save the cursor's point and reset the cursor at the right place after typing. @aktxyz could you please help to check if it fixed in your project? the version is 0.1.2.
