### ISSUE TITLE
How to change fmt on v0.3.3

### ISSUE THREAD

**Issue by stenehall** [blackbing/react-numeral-input#5]
After moving fmt out from props in https://github.com/blackbing/react-numeral-input/commit/f14188289405880a9cd5249f5181647b3be5d4d5 how are we supposed to change the format?

Atm fmt is a const that we can't pass to react-numeral-input. Or am I missing something obvious?

We can no longer do `<NumeralInput fmt="$00,00">`

**Comment by blackbing** [comment]
ooops, I thought it is not valued props. I will add it back If it is necessary props.

**Comment by blackbing** [comment]
fixed at 0.4.0
